### PR TITLE
Action versioning

### PR DESCRIPTION
**Pull request by turbomam**
I have made changes to the action-versioning branch such that the repo updates `release_*txt` files at the root of the repo whenever a release is made.

The R scripts read the  `release_*txt` files and insert the version information into any artifacts they create. I have run all of the scripts without any error.

GitHub says this branch can't be automatically merged back into master. I have reviewed all of the diffs and they are what I intended.

I'm inclined to do `git merge -X theirs`

Any objections?

### CODE REVIEW

**Comment by turbomam** [comment]
After I submitted the pull request, it was clearer that the only conflicts were in the `release_*txt` files. I think it's mergeable now.

**Comment by hjwilli** [comment]
Seems like a great start!  I would not include the date or commit status files, just the tag file to keep track of the version.

Added additional comments about future modifications (beyond this PR) to https://github.com/pennbiobank/turbo/issues/309

**Review by hjwilli — CHANGES_REQUESTED** [review]
Seems like a great start! I would not include the date or commit status files, just the tag file to keep track of the version.

**Comment by turbomam** [comment]
Thanks @hjwilli. I will 
- stop creating or injecting the date and status files (tomorrow or early next week)
- merge into master
- tag a release (1.2, because 1.1 has already been used. @cstoeckert revised that to 1.0.1, but 1.1 still appears in the release list)
- then look into commit-message based actions after that.

**Comment by hjwilli** [comment]
Regarding this -
>     * tag a release (1.2, because 1.1 has already been used. @cstoeckert revised that to 1.0.1, but 1.1 still appears in the release list)
> 
If you want, you can just [delete the incorrect tag from the command line](https://www.abeautifulsite.net/how-to-delete-a-tag-on-github).

**Pull request merged**
